### ISSUE TITLE
5 - Allow Insecure Prototype Access for Handlebars

### ISSUE THREAD

**Issue by ntch2000** [ntch2000/FoodTruck-Chasers#5]
Handlebars restricts access to objects that come directly from the database. To get around this, we must allow insecure prototype access.

1. Run npm install handlebars @handlebars/allow-prototype-access
2. Require the two new packages.
3. Update the app.engine as follows:

```
app.engine(
  "handlebars",
  exphbs({
    defaultLayout: "main",
    handlebars: allowInsecurePrototypeAccess(handlebars),
  })
);
```

**Comment by bcshanken** [comment]
@ntch2000 didnt you already finish this issue?

**Comment by scottpwells** [comment]
I thought Dennis did it. When he set the pages up. We may need to got back and do this? but let me check with Dennis

**Comment by scottpwells** [comment]
yeah its done the dependencies are notated in the package json

**Comment by bcshanken** [comment]
I am pretty sure it is done since we have been using the functionality

**Comment by dnfrancis22** [comment]
Sorry for the late reply. I had accidentally closed this issue because I confused it with the other handlebars issue. I reopened it. I thought Scott was working on it because it said that he moved it to the in progress board.
